### ISSUE TITLE
Roadmap/devlog and general discussion

### ISSUE THREAD

**Issue by notpushkin** [notpushkin/Mailspring-Libre#1]
- [ ] CI/CD (#2)
- [ ] Run Wireshark on MailSync process and ensure it doesn't connect to `id.`
- [ ] Study MailSync <-> Mailspring internal RPC protocol for future replacement (#12)
- [ ] Implement package manager (#13)

### Bring back

- [ ] [Translate](https://github.com/notpushkin/Mailspring-Libre/blob/8d5a8d2c58056139d64678a3befb716262c4ed2b/app/internal_packages/translation/lib/service.ts)
  - Use Yandex.Translate directly (prompt user for the API key)
- [ ] [Localization suggestions](https://github.com/notpushkin/Mailspring-Libre/blob/8d5a8d2c58056139d64678a3befb716262c4ed2b/app/internal_packages/localizer-help/lib/main.tsx)
- [ ] [Crash reporting](https://github.com/notpushkin/Mailspring-Libre/blob/8d5a8d2c58056139d64678a3befb716262c4ed2b/app/src/error-logger.js)
- [ ] [Update notifications](https://github.com/notpushkin/Mailspring-Libre/blob/8d5a8d2c58056139d64678a3befb716262c4ed2b/app/src/flux/stores/update-channel-store.ts)
- [ ] Investigate: [This share button](https://github.com/notpushkin/Mailspring-Libre/blob/8d5a8d2c58056139d64678a3befb716262c4ed2b/app/internal_packages/activity/lib/dashboard/share-button.tsx)
  - (I'm not sure what exactly does it share?)
- [ ] Thread sharing
  - Current implementation requires an external server
  - Perhaps we can offer to save thread as an `.html` (and `.mbox`) and let user host it somewhere?

### Properly remove

- [ ] [Newsletter](https://github.com/notpushkin/Mailspring-Libre/blob/8d5a8d2c58056139d64678a3befb716262c4ed2b/app/internal_packages/onboarding/lib/newsletter-signup.tsx)
- [ ] API client

### Won't fix:

- Link / open tracking: not possible without an external server and isn't ethically OK in my opinion

**Comment by alexanderadam** [comment]
Awesome work, @notpushkin.

I guess it would be good if this repository could add a GitHub action for automatic building the app for various platforms (for example with [`action-electron-builder`](https://github.com/marketplace/actions/electron-builder-action) [[repo](https://github.com/samuelmeuli/action-electron-builder#setup)]).

**Comment by notpushkin** [comment]
@alexanderadam I'm actually planning to gradually move away from GitHub ecosystem but a CI would definitely be nice! There's config for testing on CircleCI already, perhaps we could extend it with a packaging task?

**Comment by alexanderadam** [comment]
> There's config for testing on CircleCI already, perhaps we could extend it with a packaging task?

Sure, it seems that [there are various possibilities to push releases automatically](https://circleci.com/blog/why-continuous-integration-is-key-to-stepping-up-deployment-frequency/).

However, I just saw that CircleCI is just used for tests whereas there's already a task to [build release artifacts with Travis](https://github.com/notpushkin/Mailspring-Libre/blob/master/.travis.yml#L12-L21)

But I don't think there are pushed somewhere else than Travis itself. So I guess it would make sense to reactivate(?) Travis and then maybe just push the releases to GitHub in the end with [as described in the CircleCI blogpost](https://circleci.com/blog/why-continuous-integration-is-key-to-stepping-up-deployment-frequency/)?

Are you currently actively using Mailspring Libre? Is everything working as expected?

**Comment by notpushkin** [comment]
Thank you for your insights! A few tweaks to Travis config should do the trick (it currently fails because of some missing secrets, but that shouldn't be hard to fix). → #2

> Are you currently actively using Mailspring Libre? Is everything working as expected?

Apart from the few things outlined above, yeah! I was worried that MailSync would complain but apparently it's not that tightly coupled after all.

**Comment by alexanderadam** [comment]
I guess other points that should be added to the roadmap:

* [ ] get rid of [the closed source Mailsync component](https://github.com/notpushkin/Mailspring-Libre/blob/master/ROADMAP.md#why-is-mailsync-closed-source) and [it's questionable license](https://github.com/notpushkin/Mailspring-Libre/blob/master/LICENSE-mailsync.md) (see also the related issues [24](https://github.com/Foundry376/Mailspring/issues/24) and [1303](https://github.com/Foundry376/Mailspring/issues/1303)) - either you could ask whether **Foundry376** will open the source under a free license or it should be replaced
* [ ] GPG/PGP support (see also the related issues [25](https://github.com/Foundry376/Mailspring/issues/25), [28](https://github.com/Foundry376/Mailspring/issues/28), [940](https://github.com/Foundry376/Mailspring/issues/940) and [1240](https://github.com/Foundry376/Mailspring/issues/1240))

**Comment by notpushkin** [comment]
@alexanderadam I've had PGP in mind too! Re: Mailsync – from my earlier studies it just passes JSONs back and forth, so it shouldn't be too hard to analyze and reimplement. (Thanks for your PRs by the way – I'll take a more thorough look this evening!)

We can also tweak the [`remove-tracking-pixels`](https://github.com/notpushkin/Mailspring-Libre/tree/master/app/internal_packages/remove-tracking-pixels) package into removing _all_ tracking pixels altogether (it's not a panacea by any means but at least it's a bit of help in cases you want remote images).

**Comment by walterchris** [comment]
+1 for the PGP Support. So this Fork is for open-sourcing the remaining parts of mailspring and adding features on our own? I'd like to support implementing PGP.

**Comment by notpushkin** [comment]
Regarding PGP support, https://github.com/NgoHuy/mailspring-keybase might be a good starting point (although it didn't work for me IIRC). Anybody wanna pick it up?

> open-sourcing the remaining parts of mailspring

Eventually, I hope so!

Feature-wise, I think what we need is a proper plugin store, so that everybody can setup their client according to their needs. [It's in Mailspring's roadmap](https://github.com/Foundry376/Mailspring/blob/aa125f0136c093e0aa3deb7c46bb6433f6ede6b9/ROADMAP.md#spring-2019-planned) but apparently it's not coming anytime soon.

**Comment by notpushkin** [comment]
For those interested, you can grab a stable version with telemetry-removing patches applied [here](https://github.com/notpushkin/Mailspring-Libre/releases/tag/1.7.2-libre) (Linux only for now). 

P. S. Nightly builds are now available too! Only for Linux again, PRs welcome for Windows / macOS or (for the brave souls who fear not death) FreeBSD. To grab one, [go to Travis](https://travis-ci.com/notpushkin/Mailspring-Libre/branches), open latest `master` build and in the end of the log you'll see it in the “Deploying application” section (alright, I know, this could have been easier).

**Comment by RaitoBezarius** [comment]
First of all, insane and awesome work.

I'll try to watch this repository and contribute whatever I can, don't hesitate to mention me if you want some help for triaging issue or reproducing stuff, testing stuff (I'm an Arch Linux user on amd64 FWIW, I can maintain some upstream AUR package if you want).

> @alexanderadam I've had PGP in mind too! Re: Mailsync – from my earlier studies it just passes JSONs back and forth, so it shouldn't be too hard to analyze and reimplement. (Thanks for your PRs by the way – I'll take a more thorough look this evening!)

FWIW, the killing feature of Mailspring is MailSync, as long as MailSync can be reimplemented while thinking about battery life & performance, that'd be terrific.

**Comment by notpushkin** [comment]
Quick update: `master` has been updated with [some commits](https://github.com/notpushkin/Mailspring-Libre/compare/aed4503...c5e3bc9) from the upstream :sparkles:

**Comment by lefred** [comment]
If you want to remove all mentions to Mailspring Pro, would you just remove it in the main code or create a plugin that will override the rendering (if possible) ?
For example on the sidebar.

**Comment by notpushkin** [comment]
@lefred Good question! Overriding in plugin would be tricky I guess, but we can simulate Pro subscription by just setting the respective option in our [identity JSON](https://github.com/notpushkin/Mailspring-Libre/commit/fc0b8416601288339765d51a1814224de0b33e06) — this should remove most of the mentions. Going further, we'd probably want to remove them altogether, but this is not the priority right now.

**Comment by notpushkin** [comment]
Status update: I have translation working locally, but yet need to expose the API key field in the UI.

I also want to release this as a separate package, but it uses [cld](https://www.npmjs.com/package/@paulcbetts/cld) which can't be compiled into the js code and [isn't exposed](https://github.com/Foundry376/Mailspring/blob/master/app/src/global/mailspring-exports.d.ts) so it can't be easily used outside of the main codebase. Investigating.

**Comment by notpushkin** [comment]
Since this fork focuses on privacy, should we replace some of the mail hosts with privacy-focused ones?

![image](https://user-images.githubusercontent.com/1298948/75385087-2edf4180-58f0-11ea-919a-4949d9201d09.png)

<details>
<summary>spoiler</summary>
No, I won't actually include <a href="https://cock.li/">cock.li</a> (because of their domain names) but their <a href="https://cock.li/privacy">privacy policy</a> is pretty good. OvO
</details>

Alternatively, I was also thinking about integrating with Thunderbird's [Autoconfiguration standard](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration) – this way, we can skip this screen altogeher and just let users type in their email and password and we can pick it up from there. Thoughts?

**Comment by RaitoBezarius** [comment]
Thanks for not including cock.li ; I was pretty shocked to see this domain
again. :(

**Comment by notpushkin** [comment]
Sorry for that :( Not the best joke idea, yeah.

**Comment by RaitoBezarius** [comment]
No worries :)
We can go for ProtonMail, some classical stuff I believe :)

**Comment by louis-lau** [comment]
I thought it was quite funny 😁

**Comment by RaitoBezarius** [comment]
Supporting cock.li is akin to supporting rape.lol or hitler.rocks ; it's
difficult :(

**Comment by notpushkin** [comment]
Personally, I really dislike ProtonMail for its proprietary encryption standard and business practices: even if you wanted to use custom client, you'll have to pay for their [IMAP bridge](https://protonmail.com/bridge/) – which is another reason it doesn't make sense to add it :(

A few providers I've had in mind:
- [Disroot](https://disroot.org/en)
- [Riseup](https://riseup.net/) (currently invite-only)
- ~~[Tutanota](https://tutanota.com/)~~ open-source but doesn't support IMAP for the same “encryption” reasons as ProtonMail, sad
- [Migadu](https://www.migadu.com/en/index.html) (starting at 4 €/mo, Switzerland-based)

Now that I've thought about it, it would make sense to invite users to sign up for those instead, for existing users the Thunderbird-based “enter email/password” flow should be easier:

![image](https://user-images.githubusercontent.com/1298948/75396291-36f5ac00-5905-11ea-9ace-a173a2bbb9e8.png)

**Comment by RaitoBezarius** [comment]
I didn't know about this, actually. This is super relevant. I totally agree!

**Comment by notpushkin** [comment]
Implemented in 39ec192. Feel free to check it out [once it builds](https://travis-ci.com/notpushkin/Mailspring-Libre/builds/150763644)!

**Comment by lefred** [comment]
Nice, where can I download the draft rpm build ?
Btw, do you plan to rebase or cherry-pick from upstream for bug fixes ?
Cheers

**Comment by alexanderadam** [comment]
> Personally, I really dislike ProtonMail for its proprietary encryption standard

Can you elaborate on that? Because I thought they are using [openpgpjs](https://github.com/openpgpjs/openpgpjs) for encryption?
Also [their client](https://github.com/ProtonMail/WebClient) and most (or all?) of their [view components](https://github.com/ProtonMail?utf8=%E2%9C%93&q=&type=&language=javascript) seem to be open.
The same is true [for Tutanota](https://github.com/tutao/tutanota).

Or do you mean that they don't expose IMAP for fetching emails (which IMHO isn't related to encryption)?

**Comment by notpushkin** [comment]
@lefred The packages are built for each push to master! You can find them on the build page under [Deploying application](https://travis-ci.com/notpushkin/Mailspring-Libre/builds/150763644#L3037) section. Here are the most recent ones: [rpm](https://files.catbox.moe/ehk07g.rpm), [deb](https://files.catbox.moe/fre95m.deb)

@alexanderadam They do, just in an incompatible with other clients way :') To encrypt to outside clients, they had to invent [some kind of an intermediary page](https://protonmail.com/support/knowledge-base/encrypt-for-outside-users/). The same is true for [Tutanota](https://tutanota.com/faq#encrypted-email-external). And yeah, ProtonMail indeed is open source too – didn't know about that!

Anyhow, they both state some good reasons, like PGP not being [resistant to quantum attacks](https://tutanota.com/faq#pgp), but in my opinion this doesn't outweigh the fact that you can't easily encrypt an email to somebody on another host.

**Comment by alexanderadam** [comment]
> they had to invent some kind of an intermediary page

This is not the regular mail encryption support though. This is just if a ProtonMail user sends a message to someone _without_ GPG/PGP.
[It will use PGP if the PGP key of the recipient is known](https://protonmail.com/support/knowledge-base/how-to-use-pgp/).

You are right for Tutanota, though. [They don't support PGP](https://tutanota.com/blog/posts/innovative-encryption/#why-tutanota-does-not-rely-on-pgp).

> Anyhow, they both state some good reasons, like PGP not being resistant to quantum attacks, but in my opinion this doesn't outweigh the fact that you can't easily encrypt an email to somebody on another host.

Thank you for answering. I absolutely agree with that. :+1: I one [wrote about my opinion about email security in another comment](https://github.com/mailcow/mailcow-dockerized/issues/3134#issuecomment-557786026).

**Comment by notpushkin** [comment]
Looked into PGP implementation and it seems that it proper PGP/MIME signatures won't be possible without changes to mailsync :thinking: (https://github.com/NgoHuy/mailspring-keybase seems to do PGP Inline, which is OK but undesirable). PGP/MIME encryption could work though.

Explanation: mailsync (I believe) treats `multipart/encrypted` and `multipart/signed` just like standard emails with attachments (which is reasonable). Encrypted emails have no `text/*` part so Mailspring renders no body at all and writes everything (`encrypted.asc` and another part without filename, `PGP/MIME version identification`) as attachments to disk, so we can just read and parse it. For unencrypted messages however this isn't possible – they have a body part and the signature (`application/pgp-signature`, called `signature.asc`). The problem is that we can only get body as a sanitized string and not as raw bytes, so we can't check the signature. Bummer.

On the bright side, I believe there are some PGP-related developments in the upstream repo, so we might as well see it included after all!

**Comment by Panzki** [comment]
Hi,
I stumbled upon this project a few days ago, when checking once again if mailspring allows usage without creating an account. This is my main pain point with mailspring, I don't want send my data to some third party service.
What's the current state of this project regarding the removal of the third party service from the client?

**Comment by notpushkin** [comment]
@Panzki Right now it works without the Mailspring account and tracking calls should have been removed, although we still need to do more thorough testing of the Mailsync part. Some functionality is lost – mainly the things that depended on the Mailspring servers.

If you're on Linux, you can try out the latest `master` build ([deb](https://files.catbox.moe/s1pa83.deb), [rpm](https://files.catbox.moe/i8k3co.rpm)). For other platforms you'll have to [build from source right now](https://github.com/notpushkin/Mailspring-Libre/blob/master/CONTRIBUTING.md#build-and-run-from-source) (PRs welcome!)

**Comment by Panzki** [comment]
> although we still need to do more thorough testing of the Mailsync part.

What exactly has do be done?

**Comment by notpushkin** [comment]
@Panzki Basically my plan is to run it isolated somehow and ensure that no connections are made except than those to IMAP/SMTP servers. It isn't too high-priority for me though, as it _seems_ that Mailsync wouldn't do that kind of things (e. g. connecting to `id.getmailspring.com` even if instructed notto), at least in current builds.

**Comment by notpushkin** [comment]
We now have working macOS builds thanks to @exprez135! Latest master branch build is available [here][1], and will be added for the next release version.

Windows builds are available too [on AppVeyor][2], made possible by @louis-lau. I'll bring it into the main repo once I can lay my hand on a Windows setup to try it out.

Thank you both for your awesome work! :tada:

[1]: https://files.catbox.moe/h7jve1.dmg
[2]: https://ci.appveyor.com/project/louis-lau/mailspring-libre/build/artifacts

**Comment by Encestre** [comment]
Hi, newcommer on MailSpring here. I discovered this awesome project that pushing me forward to this  great email client.
I check the backlog here, and don't see mention on auto blocking remote image on mail opening. Is this feature looks important for you to be added to the roadmap ?

**Comment by louis-lau** [comment]
@Encestre Does this setting not do what you want?
![image](https://user-images.githubusercontent.com/1346804/83399497-9f22c500-a401-11ea-8a6f-337ed5981373.png)

**Comment by Encestre** [comment]
@louis-lau : damned, that's it ! Thanks a lot.

**Comment by Encestre** [comment]
Hi, i issue this bug : https://github.com/Foundry376/Mailspring/issues/304
Seems to be insignificant for main developer but mailspring is unusable for me due to this problem.
Does someone here have encounter this ?

**Comment by marco-brandizi** [comment]
Hi, all. Just discovered this fork. Very interesting! Any plan to make it [compatible with Microsoft 2-Factor authentication](https://github.com/Foundry376/Mailspring/issues/1118)? This has been the second reason why I gave up with Mailspring (the first being the enforcement of Mailspring ID).

**Comment by ayala-io** [comment]
> Hi, i issue this bug : [Foundry376#304](https://github.com/Foundry376/Mailspring/issues/304)
> Seems to be insignificant for main developer but mailspring is unusable for me due to this problem.
> Does someone here have encounter this ?

I discovered this fork from that exact same thread that @Encestre referenced. Very excited to see progress here. I'm primarily a Windows and macOS user so once those builds are ready, I'll be happy to try to replicate my issues from https://github.com/Foundry376/Mailspring/issues/304. Like @Encestre, the issues in that thread (and more) makes Mailspring completely unusable for me.

**Comment by louis-lau** [comment]
Windows and MacOS build have actually already been added to travis, just not yet to releases. Travis upload them to catbox.moe when done.

Latest Windows:
https://files.catbox.moe/wn3rbc.msi

Latest MacOs:
https://files.catbox.moe/6o27qn.zip

**Comment by zeigerpuppy** [comment]
> Personally, I really dislike ProtonMail for its proprietary encryption standard and business practices: even if you wanted to use custom client, you'll have to pay for their [IMAP bridge](https://protonmail.com/bridge/) – which is another reason it doesn't make sense to add it :(
> 
> A few providers I've had in mind:
> 
>     * [Disroot](https://disroot.org/en)
> 
>     * [Riseup](https://riseup.net/) (currently invite-only)
> 
>     * ~[Tutanota](https://tutanota.com/)~ open-source but doesn't support IMAP for the same “encryption” reasons as ProtonMail, sad
> 
>     * [Migadu](https://www.migadu.com/en/index.html) (starting at 4 €/mo, Switzerland-based)
> 
> 
> Now that I've thought about it, it would make sense to invite users to sign up for those instead, for existing users the Thunderbird-based “enter email/password” flow should be easier:
> 
> ![image](https://user-images.githubusercontent.com/1298948/75396291-36f5ac00-5905-11ea-9ace-a173a2bbb9e8.png)

Using thunderbird-based autoconfigure would be helpful for a lot of users but still good to fall back to manual config if auto fails.

Regarding privacy-respecting email providers, [GreenAnt](https://store.greenant.net/cart.php?gid=12) is very good too, fully IMAP/SMTP compliant.

**Comment by notpushkin** [comment]
Just an idea I've been playing around with recently: https://github.com/Mailspring-Libre/next

It's just like how [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium) or [VSCodium](https://github.com/VSCodium/vscodium) are built and _might_ be a better way than painfully rebasing our changes on top of new releases (especially if we use [codemods](https://www.npmjs.com/package/jscodeshift) instead of plaintext patches!)

cc/ @exprez135

**Comment by MichaelTunnell** [comment]
Is this client ready to be used? I see that MailSync is not open source but not sure how that relates to the Mailspring ID system. I think Mailspring is a very interesting client but I hate the requirement for the ID system and if I don't have to use that then that sounds great!

If this is a fork of Mailspring is it still going to be dependent on Mailspring in the future? I am just curious how hard of a fork this is. If it is a true hard fork then perhaps a brand change would be a good idea as to not have collision with Mailspring. Like LeapMail 
or MailJump or something like that?

**Comment by louis-lau** [comment]
I think the license on the mailsync engine only allows it to be used with something called mailspring. Without rewriting the sync engine a rename is not possible.

Seeing as @notpushkin has been playing around with patching mailspring, I'd assume this isn't meant to be a hard fork.

**Comment by alexanderadam** [comment]
> Is this client ready to be used?

People like me use it and [the release page](https://github.com/notpushkin/Mailspring-Libre/releases) has some releases.
I'm not sure what 'ready to be used' means.
I'm obviously someone who uses it and there are obviously others who're using it as well but maybe it doesn't work for you anyway. In that case you might want to create an [Issue](https://github.com/notpushkin/Mailspring-Libre/issues).

> I see that MailSync is not open source but not sure how that relates to the Mailspring ID system.

Can you pelase elaborate on that? In case something is missing, [the README](https://github.com/notpushkin/Mailspring-Libre#download-mailspring) should be extended accordingly.

> perhaps a brand change would be a good idea as to not have collision with Mailspring.

_louis-lau wrote:_

> Without rewriting the sync engine a rename is not possible.

Exactly. [notpushkin wrote a year ago](https://github.com/notpushkin/Mailspring-Libre/pull/4#issuecomment-579917074):

> MailSync license – it only allows distributing the binaries with “Mailspring” specifically, and while we don't change the app name itself, diverging the project name may be dangerous

**Comment by MichaelTunnell** [comment]
thank you very much @louis-lau & @alexanderadam for the quick responses and I understand on the branding issue. Makes sense.

The question I made about ready to use is just if it is considered production ready by the developers.

The part about the ID system is I don't want the ID system. The Mailspring ID system requires someone to create a Mailspring account and connect their emails to that account for stuff like "read receipts" and who knows what else. I was wondering if I can use this client without having to worry about the Mailspring ID system because that is really the only reason I dont use Mailspring as it is.

I know it says that this project is aimed to not do any telemetry but the MailSync stuff being proprietary and I dont know how it works with the ID system. This is why I asked because I just wanted to know how they relate to each other and if I can in fact use this fork without their ID system requirement.

**Comment by louis-lau** [comment]
Mailsync is just the imap part as I understand, not linked to mailspring services. Using it without ID is one of the most prominent reasons this fork exists :)

**Comment by marco-brandizi** [comment]
Any news about [supporting O365 2-Factor authentication](https://github.com/Foundry376/Mailspring/issues/1118)? I'd like to try this Mailspring fork but I can't use my corporate email without this feature.

**Comment by notpushkin** [comment]
Woooot!

> Great news! **Mailsync is now open source!** 🎉 In addition to this, **we *will* be making Mailspring ID optional this year.** This change is actually quite significant and involved, but it's perched right at the top of our priority list.
> — [Foundry376#33 (comment)](https://github.com/Foundry376/Mailspring/issues/33#issuecomment-775331676)

**Comment by notpushkin** [comment]
You might have noticed we've skipped a couple builds again, and that's for a good reason – **now you can use the upstream Mailspring builds without signing in to Mailspring ID!** To upgrade, install latest build from [the official website](https://getmailspring.com/), then open up the Subscription pane in settings and click Sign out. All your settings should stay in place.

(You would not be getting the Pro features though, obviously :-) @bengotow I'm hoping we can work out a privacy-friendly alternative for enabling some Pro features without Mailspring ID as well?)

I would like to thank everybody who have been involved with this little project! :heart:

**Comment by sebastian-correa** [comment]
> I would like to thank everybody who have been involved with this little project! heart

This sounds like a farewell, @notpushkin. Is the project continuing into the future? Or is the recommendation to use the regular Mailspring client?

The snooze, send later and reminder features are very useful!

(edit: Your second paragraph seems to show that development will move forwards as usual).
